lru:
	iverilog lru.v lru_tb.v
	./a.out
	gtkwave lru_tb
	rm ./a.out lru_tb
	
encoder4to2:
	iverilog encoder4to2.v encoder4to2_tb.v
	./a.out
	gtkwave encoder4to2_tb
	rm ./a.out encoder4to2_tb
	
comparator:
	iverilog comparator.v comparator_tb.v
	./a.out
	gtkwave comparator_tb
	rm ./a.out comparator_tb

singleCycle:
	iverilog singleCycle.v singleCycle_tb.v
	./a.out
	gtkwave singleCycle_tb
	rm ./a.out singleCycle_tb

